insert into EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION) values(1000,'USD','INR',75);
insert into EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION) values(1001,'GBP','INR',90);
insert into EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION) values(1002,'EUR','INR',85);